### ISSUE TITLE
Exception on narrow terminals

### ISSUE THREAD

**Issue by cdupuis** [atomist/rug-cli#198]
```Exception in thread "Thread-7" java.lang.IllegalArgumentException: Minimum abbreviation width is 4
    at org.apache.commons.lang3.StringUtils.abbreviate(StringUtils.java:7365)
    at org.apache.commons.lang3.StringUtils.abbreviate(StringUtils.java:7322)
    at com.atomist.rug.cli.output.SpinningProgressReporter.formatDetail(SpinningProgressReporter.java:108)
    at com.atomist.rug.cli.output.SpinningProgressReporter.run(SpinningProgressReporter.java:88)```

**Comment by cdupuis** [comment]
Workaround is to just make the terminal wider.
