### ISSUE TITLE
java.nio.file.InvalidPathException: Illegal char <<> at index 0: <input>

### ISSUE THREAD

**Issue by Lawouach** [atomist/rug-cli#214]
A user reported the following error whil running a rug editor on Windows today:

```
C:\stash\nova-widgets2>rug --version
rug 1.0.0-m.6
https://github.com/atomist/rug-cli.git (git revision 1ba5a17; last commit 2017-07-14)

C:\stash\nova-widgets2>rug edit atomist:rug-rugs:ConvertExistingProjectToGenerator archiveName=titan-spring-boot-service groupId=titan-rugs version=0.0.1 generatorName=NewTitanSpringBootService description="Rug generator for a Titan Spring Boot service" -X
Resolving dependencies for atomist:rug-rugs (latest.zip) completed
Reading archive structure of atomist:rug-rugs (0.32.1.zip) completed
Loading rugs of atomist:rug-rugs (0.32.1.zip) failed
java.nio.file.InvalidPathException: Illegal char <<> at index 0: <input>
        at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
        at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
        at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
        at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
        at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
        at java.nio.file.Paths.get(Paths.java:84)
        at com.atomist.source.NameAndPathElements$.apply(artifact.scala:164)
        at com.atomist.source.StringFileArtifact$.apply(StringFileArtifact.scala:59)
        at com.atomist.source.StringFileArtifact$.apply(StringFileArtifact.scala:70)
        at com.atomist.tree.pathexpression.PathExpressionParser$class.parsePathExpression(PathExpressionParser.scala:187)
        at com.atomist.tree.pathexpression.PathExpressionParser$.parsePathExpression(PathExpressionParser.scala:199)
        at com.atomist.rug.runtime.js.JavaScriptEventHandler.<init>(JavaScriptEventHandler.scala:59)
        at com.atomist.rug.runtime.js.JavaScriptEventHandlerFinder$$anonfun$create$1.apply(JavaScriptEventHandler.scala:35)
        at com.atomist.rug.runtime.js.JavaScriptEventHandlerFinder$$anonfun$create$1.apply(JavaScriptEventHandler.scala:33)
        at scala.Option.map(Option.scala:146)
        at com.atomist.rug.runtime.js.JavaScriptEventHandlerFinder.create(JavaScriptEventHandler.scala:33)
        at com.atomist.rug.runtime.js.JavaScriptRugFinder$$anonfun$find$1.apply(JavaScriptRugFinder.scala:17)
        at com.atomist.rug.runtime.js.JavaScriptRugFinder$$anonfun$find$1.apply(JavaScriptRugFinder.scala:15)
        at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
        at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
        at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
        at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
        at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:241)
        at scala.collection.AbstractTraversable.flatMap(Traversable.scala:104)
        at com.atomist.rug.runtime.js.JavaScriptRugFinder$class.find(JavaScriptRugFinder.scala:15)
        at com.atomist.rug.runtime.js.JavaScriptEventHandlerFinder.find(JavaScriptEventHandler.scala:19)
        at com.atomist.project.archive.ArchiveRugResolver$$anonfun$2.apply(ArchiveRugResolver.scala:32)
        at com.atomist.project.archive.ArchiveRugResolver$$anonfun$2.apply(ArchiveRugResolver.scala:32)
        at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
        at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
        at scala.collection.immutable.List.foreach(List.scala:381)
        at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:241)
        at scala.collection.immutable.List.flatMap(List.scala:344)
        at com.atomist.project.archive.ArchiveRugResolver.com$atomist$project$archive$ArchiveRugResolver$$find(ArchiveRugResolver.scala:32)
        at com.atomist.project.archive.ArchiveRugResolver.<init>(ArchiveRugResolver.scala:48)
        at com.atomist.rug.cli.command.AbstractCompilingAndOperationLoadingCommand.lambda$createRugResolver$1(AbstractCompilingAndOperationLoadingCommand.java:69)
        at com.atomist.rug.cli.output.ProgressReportingOperationRunner.run(ProgressReportingOperationRunner.java:22)
        at com.atomist.rug.cli.command.AbstractCompilingAndOperationLoadingCommand.createRugResolver(AbstractCompilingAndOperationLoadingCommand.java:67)
        at com.atomist.rug.cli.command.AbstractCompilingAndOperationLoadingCommand.run(AbstractCompilingAndOperationLoadingCommand.java:157)
        at com.atomist.rug.cli.command.AbstractCommand.run(AbstractCommand.java:36)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.atomist.rug.cli.command.ReflectiveCommandRunMethodRunner.invokeCommand(ReflectiveCommandRunMethodRunner.java:17)
        at com.atomist.rug.cli.command.ReflectiveCommandRunner.invokeReflectiveCommand(ReflectiveCommandRunner.java:93)
        at com.atomist.rug.cli.command.ReflectiveCommandRunner.invokeCommand(ReflectiveCommandRunner.java:262)
        at com.atomist.rug.cli.command.ReflectiveCommandRunner.runCommand(ReflectiveCommandRunner.java:60)
        at com.atomist.rug.cli.Runner.runCommand(Runner.java:93)
        at com.atomist.rug.cli.Runner.run(Runner.java:40)
        at com.atomist.rug.cli.Main.invokeRunner(Main.java:34)
        at com.atomist.rug.cli.Main.main(Main.java:25)
```

I was able to reproduce this issue with a describe command too (using rug-cli 1.0.0-m5):

```
$ rug describe archive atomist:rug-rugs -X
Resolving dependencies for atomist:rug-rugs (latest.zip) completed
Reading archive structure of atomist:rug-rugs (0.32.1.zip) completed
Loading rugs of atomist:rug-rugs (0.32.1.zip) failed

java.nio.file.InvalidPathException: Illegal char <<> at index 0: <input>
        at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
        at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
        at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
        at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
        at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
        at java.nio.file.Paths.get(Paths.java:84)
        at com.atomist.source.NameAndPathElements$.apply(artifact.scala:164)
        at com.atomist.source.StringFileArtifact$.apply(StringFileArtifact.scala:59)
        at com.atomist.source.StringFileArtifact$.apply(StringFileArtifact.scala:70)
        at com.atomist.tree.pathexpression.PathExpressionParser$class.parsePathExpression(PathExpressionParser.scala:187)
        at com.atomist.tree.pathexpression.PathExpressionParser$.parsePathExpression(PathExpressionParser.scala:199)
        at com.atomist.rug.runtime.js.JavaScriptEventHandler.<init>(JavaScriptEventHandler.scala:59)
        at com.atomist.rug.runtime.js.JavaScriptEventHandlerFinder$$anonfun$create$1.apply(JavaScriptEventHandler.scala:35)
        at com.atomist.rug.runtime.js.JavaScriptEventHandlerFinder$$anonfun$create$1.apply(JavaScriptEventHandler.scala:33)
        at scala.Option.map(Option.scala:146)
        at com.atomist.rug.runtime.js.JavaScriptEventHandlerFinder.create(JavaScriptEventHandler.scala:33)
        at com.atomist.rug.runtime.js.JavaScriptRugFinder$$anonfun$find$1.apply(JavaScriptRugFinder.scala:17)
        at com.atomist.rug.runtime.js.JavaScriptRugFinder$$anonfun$find$1.apply(JavaScriptRugFinder.scala:15)
        at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
        at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
        at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
        at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
        at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:241)
        at scala.collection.AbstractTraversable.flatMap(Traversable.scala:104)
        at com.atomist.rug.runtime.js.JavaScriptRugFinder$class.find(JavaScriptRugFinder.scala:15)
        at com.atomist.rug.runtime.js.JavaScriptEventHandlerFinder.find(JavaScriptEventHandler.scala:19)
        at com.atomist.project.archive.ArchiveRugResolver$$anonfun$2.apply(ArchiveRugResolver.scala:32)
        at com.atomist.project.archive.ArchiveRugResolver$$anonfun$2.apply(ArchiveRugResolver.scala:32)
        at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
        at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
        at scala.collection.immutable.List.foreach(List.scala:381)
        at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:241)
        at scala.collection.immutable.List.flatMap(List.scala:344)
        at com.atomist.project.archive.ArchiveRugResolver.com$atomist$project$archive$ArchiveRugResolver$$find(ArchiveRugResolver.scala:32)
        at com.atomist.project.archive.ArchiveRugResolver.<init>(ArchiveRugResolver.scala:48)
        at com.atomist.rug.cli.command.AbstractCompilingAndOperationLoadingCommand.lambda$createRugResolver$1(AbstractCompilingAndOperationLoadingCommand.java:69)
        at com.atomist.rug.cli.output.ProgressReportingOperationRunner.run(ProgressReportingOperationRunner.java:22)
        at com.atomist.rug.cli.command.AbstractCompilingAndOperationLoadingCommand.createRugResolver(AbstractCompilingAndOperationLoadingCommand.java:67)
        at com.atomist.rug.cli.command.AbstractCompilingAndOperationLoadingCommand.run(AbstractCompilingAndOperationLoadingCommand.java:156)
        at com.atomist.rug.cli.command.AbstractCommand.run(AbstractCommand.java:36)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.atomist.rug.cli.command.ReflectiveCommandRunMethodRunner.invokeCommand(ReflectiveCommandRunMethodRunner.java:17)
        at com.atomist.rug.cli.command.ReflectiveCommandRunner.invokeReflectiveCommand(ReflectiveCommandRunner.java:93)
        at com.atomist.rug.cli.command.ReflectiveCommandRunner.invokeCommand(ReflectiveCommandRunner.java:262)
        at com.atomist.rug.cli.command.ReflectiveCommandRunner.runCommand(ReflectiveCommandRunner.java:60)
        at com.atomist.rug.cli.Runner.runCommand(Runner.java:93)
        at com.atomist.rug.cli.Runner.run(Runner.java:40)
        at com.atomist.rug.cli.Main.invokeRunner(Main.java:34)
        at com.atomist.rug.cli.Main.main(Main.java:25)
```

I could reproduce this issue with spring-team-handlers.

However, I didn't get that exception on spring-rugs:

```
$ rug describe archive atomist:spring-rugs -X
Resolving dependencies for atomist:spring-rugs (latest.zip) completed
Reading archive structure of atomist:spring-rugs (0.13.3.zip) completed
Loading rugs of atomist:spring-rugs (0.13.3.zip) completed

atomist:spring-rugs (0.13.3)

> Archive
  ~\.atomist/repository/atomist/spring-rugs/0.13.3/spring-rugs-0.13.3.zip (8 mb in 4238 files)

> Generators
  NewSpringBootRestService
    Creates a new Spring Boot REST service project

> Requires
  [1.0.0-m.5,2.0.0)

To get more information on any of the Rugs listed above, run:
  rug describe editor|generator|command-handler|event-handler|response-handler|integration-test|function atomist:spring-rugs:NAME
```

Not certain how those rug archives differ.

**Comment by Lawouach** [comment]
So this fails when loading event handler, which is why it doesn't fail on `spring-rugs` which doesn't have any.

**Comment by Lawouach** [comment]
I thought I would try directly from the `ru-rugs` repo cloned on my machine but here is the error I'm now getting:

```
$ rug describe -l
Resolving dependencies for atomist:rug-rugs (0.32.1.local) completed
Compiling source files of atomist:rug-rugs (0.32.1.local) - AddFunctions.ts... Compiled .atomist/editors/AddFunctions.ts failed
Compiling source files of atomist:rug-rugs (0.32.1.local) - AddLicense.ts (... Compiled .atomist/editors/AddLicense.ts failed
Compiling source files of atomist:rug-rugs (0.32.1.local) / AddLocalEditor.... Compiled .atomist/editors/AddLocalEditor.ts failed
Compiling source files of atomist:rug-rugs (0.32.1.local) - AddTypeScriptCo... Compiled .atomist/editors/AddTypeScriptCommandHandler.ts failed
Compiling source files of atomist:rug-rugs (0.32.1.local) | AddTypeScriptEd... Compiled .atomist/editors/AddTypeScriptEditor.ts failed
Compiling source files of atomist:rug-rugs (0.32.1.local) / AddTypeScriptEv... Compiled .atomist/editors/AddTypeScriptEventHandler.ts failed
Compiling source files of atomist:rug-rugs (0.32.1.local) - AddTypeScriptGe... Compiled .atomist/editors/AddTypeScriptGenerator.ts failed
Compiling source files of atomist:rug-rugs (0.32.1.local) \ BumpVersion.ts ... Compiled .atomist/editors/BumpVersion.ts failed
Compiling source files of atomist:rug-rugs (0.32.1.local) \ ConvertExisting... Compiled .atomist/editors/ConvertExistingProjectToGenerator.ts failed
Compiling source files of atomist:rug-rugs (0.32.1.local) / ConvertExisting... Compiled .atomist/editors/ConvertExistingProjectToRugArchive.ts failed
Compiling source files of atomist:rug-rugs (0.32.1.local) / ConvertManifest... Compiled .atomist/editors/ConvertManifestToPackageJson.ts failed
Compiling source files of atomist:rug-rugs (0.32.1.local) - HavePathExpress... Compiled .atomist/editors/HavePathExpressionEngine.ts failed
Compiling source files of atomist:rug-rugs (0.32.1.local) / RugEditorsPredi... Compiled .atomist/editors/RugEditorsPredicates.ts failed
Compiling source files of atomist:rug-rugs (0.32.1.local) | RugParameters.t... Compiled .atomist/editors/RugParameters.ts failed
Compiling source files of atomist:rug-rugs (0.32.1.local) | TypeScriptEdito... Compiled .atomist/editors/TypeScriptEditor.ts failed
Compiling source files of atomist:rug-rugs (0.32.1.local) / UpdateRug.ts (.... Compiled .atomist/editors/UpdateRug.ts failed
Compiling source files of atomist:rug-rugs (0.32.1.local) - UpdateSupportFi... Compiled .atomist/editors/UpdateSupportFiles.ts failed
Compiling source files of atomist:rug-rugs (0.32.1.local) | NewRugProject.t... Compiled .atomist/generators/NewRugProject.ts failed
Compiling source files of atomist:rug-rugs (0.32.1.local) - NewStarterRugPr... Compiled .atomist/generators/NewStarterRugProject.ts failed
Compiling source files of atomist:rug-rugs (0.32.1.local) \ RugGeneratorFun... Compiled .atomist/generators/RugGeneratorFunctions.ts failed
Compiling source files of atomist:rug-rugs (0.32.1.local) \ TypeScriptGener... Compiled .atomist/generators/TypeScriptGenerator.ts failed
Compiling source files of atomist:rug-rugs (0.32.1.local) \ ShowLatestVersi... Compiled .atomist/handlers/command/ShowLatestVersions.ts failed
Compiling source files of atomist:rug-rugs (0.32.1.local) / TypeScriptComma... Compiled .atomist/handlers/command/TypeScriptCommandHandler.ts failed
Compiling source files of atomist:rug-rugs (0.32.1.local) - TypeScriptEvent... Compiled .atomist/handlers/event/TypeScriptEventHandler.ts failed
Compiling source files of atomist:rug-rugs (0.32.1.local) / HttpClient.ts (... Compiled .atomist/handlers/util/HttpClient.ts failed
Compiling source files of atomist:rug-rugs (0.32.1.local) - AddFunctionsTes... Compiled .atomist/mocha/AddFunctionsTest.ts failed
Compiling source files of atomist:rug-rugs (0.32.1.local) | IncrementVersio... Compiled .atomist/mocha/IncrementVersionTest.ts failed
Compiling source files of atomist:rug-rugs (0.32.1.local) - SimpleTest.ts (... Compiled .atomist/mocha/SimpleTest.ts failed
Compiling source files of atomist:rug-rugs (0.32.1.local) - TypeScriptComma... Compiled .atomist/tests/handlers/command/TypeScriptCommandHandlerSteps.ts failed
Compiled .atomist/tests/handlers/event/TypeScriptEventHandlerSteps.ts failedCompiling source files of atomist:rug-rugs (0.32.1.local) \ TypeScriptEvent...
Compiling source files of atomist:rug-rugs (0.32.1.local) - AddLicenseSteps... Compiled .atomist/tests/project/AddLicenseSteps.ts failed
Compiling source files of atomist:rug-rugs (0.32.1.local) \ AddLocalEditorS... Compiled .atomist/tests/project/AddLocalEditorSteps.ts failed
Compiling source files of atomist:rug-rugs (0.32.1.local) \ AddTypeScriptCo... Compiled .atomist/tests/project/AddTypeScriptCommandHandlerSteps.ts failed
Compiling source files of atomist:rug-rugs (0.32.1.local) \ AddTypeScriptEd... Compiled .atomist/tests/project/AddTypeScriptEditorSteps.ts failed
Compiling source files of atomist:rug-rugs (0.32.1.local) \ AddTypeScriptEv... Compiled .atomist/tests/project/AddTypeScriptEventHandlerSteps.ts failed
Compiling source files of atomist:rug-rugs (0.32.1.local) \ AddTypeScriptGe... Compiled .atomist/tests/project/AddTypeScriptGeneratorSteps.ts failed
Compiling source files of atomist:rug-rugs (0.32.1.local) \ BumpVersionStep... Compiled .atomist/tests/project/BumpVersionSteps.ts failed
Compiling source files of atomist:rug-rugs (0.32.1.local) \ ConvertExisting... Compiled .atomist/tests/project/ConvertExistingProjectToGeneratorSteps.ts failed
Compiling source files of atomist:rug-rugs (0.32.1.local) \ ConvertExisting... Compiled .atomist/tests/project/ConvertExistingProjectToRugArchiveSteps.ts failed
Compiling source files of atomist:rug-rugs (0.32.1.local) | ConvertManifest... Compiled .atomist/tests/project/ConvertManifestToPackageJsonSteps.ts failed
Compiling source files of atomist:rug-rugs (0.32.1.local) | HavePathExpress... Compiled .atomist/tests/project/HavePathExpressionEngineSteps.ts failed
Compiling source files of atomist:rug-rugs (0.32.1.local) | NewRugProjectSt... Compiled .atomist/tests/project/NewRugProjectSteps.ts failed
Compiling source files of atomist:rug-rugs (0.32.1.local) \ NewStarterRugPr... Compiled .atomist/tests/project/NewStarterRugProjectSteps.ts failed
Compiling source files of atomist:rug-rugs (0.32.1.local) \ TypeScriptEdito... Compiled .atomist/tests/project/TypeScriptEditorSteps.ts failed
Compiling source files of atomist:rug-rugs (0.32.1.local) \ TypeScriptGener... Compiled .atomist/tests/project/TypeScriptGeneratorSteps.ts failed
Compiling source files of atomist:rug-rugs (0.32.1.local) \ UpdateRugSteps.... Compiled .atomist/tests/project/UpdateRugSteps.ts failed
Compiling source files of atomist:rug-rugs (0.32.1.local) \ UpdateSupportFi... Compiled .atomist/tests/project/UpdateSupportFilesSteps.ts failed
Compiling source files of atomist:rug-rugs (0.32.1.local) failed

Source for .atomist/editors/AddFunctions.js couldn't be found
Source for .atomist/editors/AddLicense.js couldn't be found
Source for .atomist/editors/AddLocalEditor.js couldn't be found
Source for .atomist/editors/AddTypeScriptCommandHandler.js couldn't be found
Source for .atomist/editors/AddTypeScriptEditor.js couldn't be found
Source for .atomist/editors/AddTypeScriptEventHandler.js couldn't be found
Source for .atomist/editors/AddTypeScriptGenerator.js couldn't be found
Source for .atomist/editors/BumpVersion.js couldn't be found
Source for .atomist/editors/ConvertExistingProjectToGenerator.js couldn't be found
Source for .atomist/editors/ConvertExistingProjectToRugArchive.js couldn't be found
Source for .atomist/editors/ConvertManifestToPackageJson.js couldn't be found
Source for .atomist/editors/HavePathExpressionEngine.js couldn't be found
Source for .atomist/editors/RugEditorsPredicates.js couldn't be found
Source for .atomist/editors/RugParameters.js couldn't be found
Source for .atomist/editors/TypeScriptEditor.js couldn't be found
Source for .atomist/editors/UpdateRug.js couldn't be found
Source for .atomist/editors/UpdateSupportFiles.js couldn't be found
Source for .atomist/generators/NewRugProject.js couldn't be found
Source for .atomist/generators/NewStarterRugProject.js couldn't be found
Source for .atomist/generators/RugGeneratorFunctions.js couldn't be found
Source for .atomist/generators/TypeScriptGenerator.js couldn't be found
Source for .atomist/handlers/command/ShowLatestVersions.js couldn't be found
Source for .atomist/handlers/command/TypeScriptCommandHandler.js couldn't be found
Source for .atomist/handlers/event/TypeScriptEventHandler.js couldn't be found
Source for .atomist/handlers/util/HttpClient.js couldn't be found
Source for .atomist/mocha/AddFunctionsTest.js couldn't be found
Source for .atomist/mocha/IncrementVersionTest.js couldn't be found
Source for .atomist/mocha/SimpleTest.js couldn't be found
Source for .atomist/tests/handlers/command/TypeScriptCommandHandlerSteps.js couldn't be found
Source for .atomist/tests/handlers/event/TypeScriptEventHandlerSteps.js couldn't be found
Source for .atomist/tests/project/AddLicenseSteps.js couldn't be found
Source for .atomist/tests/project/AddLocalEditorSteps.js couldn't be found
Source for .atomist/tests/project/AddTypeScriptCommandHandlerSteps.js couldn't be found
Source for .atomist/tests/project/AddTypeScriptEditorSteps.js couldn't be found
Source for .atomist/tests/project/AddTypeScriptEventHandlerSteps.js couldn't be found
Source for .atomist/tests/project/AddTypeScriptGeneratorSteps.js couldn't be found
Source for .atomist/tests/project/BumpVersionSteps.js couldn't be found
Source for .atomist/tests/project/ConvertExistingProjectToGeneratorSteps.js couldn't be found
Source for .atomist/tests/project/ConvertExistingProjectToRugArchiveSteps.js couldn't be found
Source for .atomist/tests/project/ConvertManifestToPackageJsonSteps.js couldn't be found
Source for .atomist/tests/project/HavePathExpressionEngineSteps.js couldn't be found
Source for .atomist/tests/project/NewRugProjectSteps.js couldn't be found
Source for .atomist/tests/project/NewStarterRugProjectSteps.js couldn't be found
Source for .atomist/tests/project/TypeScriptEditorSteps.js couldn't be found
Source for .atomist/tests/project/TypeScriptGeneratorSteps.js couldn't be found
Source for .atomist/tests/project/UpdateRugSteps.js couldn't be found
Source for .atomist/tests/project/UpdateSupportFilesSteps.js couldn't be found
```

Not sure if it's related or if this helps.

**Comment by Lawouach** [comment]
Moved to artifact-source.
