### ISSUE TITLE
Allow node_modules to be loaded when run from rug editor project root

### ISSUE THREAD

**Issue by kipz** [atomist/rug-cli#27]
From the .atomist directory the editor runs fine:
```
17:04 [licensing-editors/.atomist] $ rug edit -X -l -C /tmp AddLicenseFile licenseName="agpl-3.0"
Resolving dependencies for atomist-rugs:licensing-editors:0.1.0 ← local completed
Cannot find module buffer
Loading atomist-rugs:licensing-editors:0.1.0 ← local into runtime completed
Running editor AddLicenseFile of atomist-rugs:licensing-editors:0.1.0 ← local completed

→ Project
  /tmp (17mb in 35 files)
```

But from the project root, resolution fails:
```
17:00 [licensing-editors] $ rug edit -X -l -C /tmp AddLicenseFile licenseName="agpl-3.0"
Resolving dependencies for atomist-rugs:licensing-editors:0.1.0 ← local completed
Cannot find module js-yaml
Loading atomist-rugs:licensing-editors:0.1.0 ← local into runtime failed

javax.script.ScriptException: Error: Cannot find module js-yaml in <eval> at line number 91 at column number 12
	at jdk.nashorn.api.scripting.NashornScriptEngine.throwAsScriptException(NashornScriptEngine.java:467)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:451)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:403)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:399)
	at jdk.nashorn.api.scripting.NashornScriptEngine.eval(NashornScriptEngine.java:155)
	at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)
	at com.atomist.rug.runtime.js.JavaScriptContext.eval(JavaScriptContext.scala:35)
	at com.atomist.rug.runtime.js.JavaScriptContext.eval(JavaScriptContext.scala:44)
	at com.atomist.rug.runtime.js.JavaScriptOperationFinder$$anonfun$fromTypeScriptArchive$2.apply(JavaScriptOperationFinder.scala:44)
	at com.atomist.rug.runtime.js.JavaScriptOperationFinder$$anonfun$fromTypeScriptArchive$2.apply(JavaScriptOperationFinder.scala:42)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at com.atomist.rug.runtime.js.JavaScriptOperationFinder$.fromTypeScriptArchive(JavaScriptOperationFinder.scala:42)
	at com.atomist.project.archive.ProjectOperationArchiveReader.findOperations(ProjectOperationArchiveReader.scala:36)
	at com.atomist.rug.loader.DefaultOperationsLoader.loadArtifact(DefaultOperationsLoader.java:161)
	at com.atomist.rug.loader.DefaultOperationsLoader.load(DefaultOperationsLoader.java:84)
	at com.atomist.rug.cli.command.AbstractCommand.doLoadOperations(AbstractCommand.java:89)
	at com.atomist.rug.cli.command.AbstractCommand.lambda$loadOperations$0(AbstractCommand.java:82)
	at com.atomist.rug.cli.output.ProgressReportingOperationRunner.run(ProgressReportingOperationRunner.java:20)
	at com.atomist.rug.cli.command.AbstractCommand.loadOperations(AbstractCommand.java:80)
	at com.atomist.rug.cli.command.AbstractCommand.loadOperationsAndInvokeRun(AbstractCommand.java:113)
	at com.atomist.rug.cli.command.AbstractCommand.run(AbstractCommand.java:53)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.atomist.rug.cli.command.ReflectiveCommandRunMethodRunner.invokeCommand(ReflectiveCommandRunMethodRunner.java:20)
	at com.atomist.rug.cli.command.ReflectiveCommandRunner.runCommand(ReflectiveCommandRunner.java:69)
	at com.atomist.rug.cli.Runner.runCommand(Runner.java:122)
	at com.atomist.rug.cli.Runner.run(Runner.java:44)
	at com.atomist.rug.cli.Main.main(Main.java:17)
Caused by: <eval>:91:12 Error: Cannot find module js-yaml
	at jdk.nashorn.internal.runtime.ECMAException.create(ECMAException.java:113)
	at jdk.nashorn.internal.scripts.Script$Recompilation$5$2620AA$\^eval\_.L:21$Require(<eval>:91)
	at jdk.nashorn.internal.scripts.Script$4$\^eval\_.:program(<eval>:22)
	at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:637)
	at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:494)
	at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:393)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:446)
	... 29 more
```

**Comment by cdupuis** [comment]
With latest typescript compiler 0.4.3 this is fixed.
