### ISSUE TITLE
NoSuchMethodError when running edit

### ISSUE THREAD

**Issue by dandew** [atomist/rug-cli#28]
Facing the following issue when trying to use `atomist-rugs:common-editors:AddReadme`

```
$ rug -v
rug 0.15.1
atomist/rug-cli.git (git revision 48fbb9a: last commit 2016-12-06)

$ uname -a
Linux development 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt20-1+deb8u1 (2015-12-14) x86_64 GNU/Linux

$ rug -X edit atomist-rugs:common-editors:AddReadme
Downloading atomist-rugs/common-editors/maven-metadata.xml ← maven-central (0kb) failed                                                                              
Downloading atomist-rugs/common-editors/maven-metadata.xml ← rug-types (0kb) failed                                                                                  
Resolving dependencies for atomist-rugs:common-editors:latest completed
Loading atomist-rugs:common-editors:0.1.0 into runtime failed

java.lang.NoSuchMethodError: com.atomist.project.archive.ProjectOperationArchiveReader.findOperations(Lcom/atomist/source/ArtifactSource;Lscala/Option;Lscala/collection/Seq;)Lcom/atomist/project/archive/Operations;
	at com.atomist.rug.loader.DefaultOperationsLoader.loadArtifact(DefaultOperationsLoader.java:161)
	at com.atomist.rug.loader.DefaultOperationsLoader.load(DefaultOperationsLoader.java:84)
	at com.atomist.rug.cli.command.AbstractCommand.doLoadOperations(AbstractCommand.java:89)
	at com.atomist.rug.cli.command.AbstractCommand.lambda$loadOperations$2(AbstractCommand.java:82)
	at com.atomist.rug.cli.output.ProgressReportingOperationRunner.run(ProgressReportingOperationRunner.java:20)
	at com.atomist.rug.cli.command.AbstractCommand.loadOperations(AbstractCommand.java:80)
	at com.atomist.rug.cli.command.AbstractCommand.loadOperationsAndInvokeRun(AbstractCommand.java:113)
	at com.atomist.rug.cli.command.AbstractCommand.run(AbstractCommand.java:53)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.atomist.rug.cli.command.ReflectiveCommandRunMethodRunner.invokeCommand(ReflectiveCommandRunMethodRunner.java:20)
	at com.atomist.rug.cli.command.ReflectiveCommandRunner.runCommand(ReflectiveCommandRunner.java:69)
	at com.atomist.rug.cli.Runner.runCommand(Runner.java:122)
	at com.atomist.rug.cli.Runner.run(Runner.java:44)
	at com.atomist.rug.cli.Main.main(Main.java:17)
```

**Comment by antoine-atmire** [comment]
Same here with a describe command. It worked yesterday. I updated the rug-cli with apt-get but no change.


```
$ rug -v
rug 0.15.1
atomist/rug-cli.git (git revision 48fbb9a: last commit 2016-12-06)

$ uname -a
Linux antoine 4.8.0-28-generic #30-Ubuntu SMP Fri Nov 11 14:03:52 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

$ java -version
openjdk version "1.8.0_111"
OpenJDK Runtime Environment (build 1.8.0_111-8u111-b14-2ubuntu0.16.10.2-b14)
OpenJDK 64-Bit Server VM (build 25.111-b14, mixed mode)                                                                                   4d ⚑  

$ rug describe archive atomist-rugs:common-editors -X
Downloading atomist-rugs/common-editors/maven-metadata.xml ← maven-central (0kb) failed
Downloading atomist-rugs/common-editors/maven-metadata.xml ← rug-types (0kb) failed
Resolving dependencies for atomist-rugs:common-editors:latest completed
Loading atomist-rugs:common-editors:0.1.0 into runtime failed

java.lang.NoSuchMethodError: com.atomist.project.archive.ProjectOperationArchiveReader.findOperations(Lcom/atomist/source/ArtifactSource;Lscala/Option;Lscala/collection/Seq;)Lcom/atomist/project/archive/Operations;
        at com.atomist.rug.loader.DefaultOperationsLoader.loadArtifact(DefaultOperationsLoader.java:161)
        at com.atomist.rug.loader.DefaultOperationsLoader.load(DefaultOperationsLoader.java:84)
        at com.atomist.rug.cli.command.AbstractCommand.doLoadOperations(AbstractCommand.java:89)
        at com.atomist.rug.cli.command.AbstractCommand.lambda$loadOperations$2(AbstractCommand.java:82)
        at com.atomist.rug.cli.output.ProgressReportingOperationRunner.run(ProgressReportingOperationRunner.java:20)
        at com.atomist.rug.cli.command.AbstractCommand.loadOperations(AbstractCommand.java:80)
        at com.atomist.rug.cli.command.AbstractCommand.loadOperationsAndInvokeRun(AbstractCommand.java:113)
        at com.atomist.rug.cli.command.AbstractCommand.run(AbstractCommand.java:53)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.atomist.rug.cli.command.ReflectiveCommandRunMethodRunner.invokeCommand(ReflectiveCommandRunMethodRunner.java:20)
        at com.atomist.rug.cli.command.ReflectiveCommandRunner.runCommand(ReflectiveCommandRunner.java:69)
        at com.atomist.rug.cli.Runner.runCommand(Runner.java:122)
        at com.atomist.rug.cli.Runner.run(Runner.java:44)
        at com.atomist.rug.cli.Main.main(Main.java:17)
```

**Comment by cdupuis** [comment]
The API of `ProjectOperationArchiveReader.findOperations` changed in an incompatible way. See https://github.com/atomist/rug/commit/f814e122cb17950474b082c38050964c0ad29ca4.

We'll have to absorb the new API and release a new CLI version.

**Comment by cdupuis** [comment]
I'll address this now and release a new version with a fix for that. 

@dandew @antoine-atmire Thanks for taking the time to report this.

**Comment by cdupuis** [comment]
Please update your CLI to 0.16.0.
