### ISSUE TITLE
ManifestException when parent is another git repository

### ISSUE THREAD

**Issue by antoine-atmire** [atomist/rug-cli#44]
I made a new project with some existing sources, added a .gitignore file to ignore the .atomist folder.
Then I cloned my atomist folder in `my-project/.atomist`.

Now `rug test` fails.

```
rug test -X

com.atomist.rug.manifest.ManifestException: No manifest.yml or package.json found in .atomist folder
        at com.atomist.rug.manifest.ManifestFactory.read(ManifestFactory.java:22)
        at com.atomist.rug.cli.command.AbstractLocalArtifactDescriptorProvider.artifactDescriptor(AbstractLocalArtifactDescriptorProvider.java:39)
        at com.atomist.rug.cli.command.ReflectiveCommandRunner.runCommand(ReflectiveCommandRunner.java:45)
        at com.atomist.rug.cli.Runner.runCommand(Runner.java:122)
        at com.atomist.rug.cli.Runner.run(Runner.java:44)
        at com.atomist.rug.cli.Main.main(Main.java:17)
```

I assure you there is a manifest.yml present. In fact when I move `my-project/.git` somewhere else `rug test` works.

I am testing this with the rug-cli version 0.17.2

**Comment by cdupuis** [comment]
Hmm, that is kind of expected behaviour as our source code abstraction considers `.gitignore`. So when you ignore the `.atomist` directory, you're essentially also ignoring `.atomist` when running the CLI.

Why would you ignore the `.atomist` folder?

**Comment by cdupuis** [comment]
Ah, wait. I think there is more here. Could you please provide a tree of your directory layout? I think I'm not sure I'm fully understanding your setup.

**Comment by antoine-atmire** [comment]
I have `.atomist` in its own git repository so I would be able to clone it in multiple similar projects and pull updates to `.atomist` in each of them. Kind of as a submodule, but I simply cloned and added it to .gitignore rather than using git submodules.

**Comment by antoine-atmire** [comment]
```
tree -a -L 2                                                                                                                                      
.                                                                                                                                                 
├── .atomist                                                                                                                                      
│   ├── editors                                                                                                                                   
│   ├── .git                                                                                                                                      
│   ├── .gitignore                                                                                                                                
│   ├── manifest.yml                                                                                                                              
│   ├── templates                                                                                                                                 
│   └── tests                                                                                                                                     
├── code-directory                                                                                                                                
│   ├── ...                                                                                                                                       
│   └── ...                                                                                                                                       
├── .git                                                                                                                                          
│   ├── ...                                                                                                                                       
│   └── ...                                                                                                                                       
├── .gitignore                                                                                                                                    
├── LICENSE                                                                                                                                       
├── NOTICE                                                                                                                                        
├── pom.xml                                                                                                                                       
└── README    
```

**Comment by cdupuis** [comment]
hmm, I get that now. 

May I ask for a little background on why you choose to share a `.atomist` folder like that? I'm trying to understand the use-case a bit to figure out how we can support you.

**Comment by cdupuis** [comment]
Looks like we found a workable solution which is based on a reusable Rug archive rather then copying the `.atomist` into every project.
